### ISSUE TITLE
Is there any restriction when the results returns? such as NEARBY eq.

### ISSUE THREAD

**Issue by yorkxiao** [tidwall/tile38#203]
Hi, tidwall,
When I test NEARBY command, I set more than 100000 ids with a FIELD **update_time_utc**, then I want to get the COUNT of records within five minutes of **update_time_utc** FIELD. But I found that it seems no more than 100000 results will be returned. 

> 127.0.0.1:9851> NEARBY locations LIMIT 100009 COUNT POINT 21.162 103.268 600000000
> {"ok":true,**"count":100000**,"cursor":0,"elapsed":"117.1875ms"}

Is there any restriction of this scene? Can you remove this restriction, especially commands with COUNT option?

**Comment by tidwall** [comment]
Yes there is a hard upper limit on the number of results. This is to keep runaway queries from locking collections and halting the service. 

But I agree that it should not exist for COUNT. I'll look into it further. It's possible that we can lift this restriction.

**Comment by FX-HAO** [comment]
@tidwall The upper limit should be documented, it confused me a lot, and is there any formula about 
 the upper limit?

**Comment by tidwall** [comment]
The upper limit is set [here](https://github.com/tidwall/tile38/blob/master/controller/scanner.go#L17). I plan on making changes to allow for this limit to be lifted for the purpose of COUNT.

**Comment by FX-HAO** [comment]
@tidwall Sorry, my problem seems like a new one. I have a dataset which has more than 50 points but less than 1000 points. With the following command: 

```
tile38:9851> STATS SCAN stops
1) (nil)
2) 1) "in_memory_size"
   2) "1668"
   3) "num_objects"
   4) "93"
   5) "num_points"
   6) "93"
   7) "num_strings"
   8) "0"

tile38:9851> NEARBY stops LIMIT 1000 DISTANCE POINT 23.710007 117.175871
```

I expect all the points will be returned in ascending order, but i got 17 points returned.

**Comment by tidwall** [comment]
@FX-HAO No worries, I would like to reproduce this issue. Are the 93 point relatively nearby each other?

**Comment by FX-HAO** [comment]
@tidwall Yes, the most of points are quite close to each other(less than 100 meters). And i can provide you my dataset if you need it.  😊

**Comment by tidwall** [comment]
@FX-HAO your ur dataset would be very helpful. Thank you.

**Comment by FX-HAO** [comment]
[appendonly.aof.zip](https://github.com/tidwall/tile38/files/1213631/appendonly.aof.zip)

@tidwall The command:

```
tile38:9851> NEARBY stops LIMIT 1000 DISTANCE POINT 23.710007 117.175871
```

**Comment by tidwall** [comment]
@FX-HAO thanks!

**Comment by tidwall** [comment]
@FX-HAO Please try the latest master branch. I made some changes recently that should fix this issue.

**Comment by tidwall** [comment]
@yorkxiao I just pushed an update that fixes the problem when LIMIT and COUNT are used together. Please reopen this issue if you see further problems.

**Comment by FX-HAO** [comment]
@tidwall I tried the latest version of docker image, the problem is still not resolved.

**Comment by tidwall** [comment]
Sorry but right now this update is only from the master branch. I hope to tag a new release of Tile38 soon. At which point the official docker image will be updated too.

**Comment by tidwall** [comment]
@FX-HAO I just pushed and official release so an updated Docker image should be available now.

**Comment by FX-HAO** [comment]
@tidwall Awesome, it works correctly, thanks.
